# File: action.yml
name: 'Determine Execution Path'
description: 'Determine the execution path based on files modified and services used'

inputs:
  files-modified:
    description: 'Path to files-modified.json'
    required: true
  services-used:
    description: 'Path to services-used.json'
    required: true
outputs:
  execution-path:
    description: 'Execution path based on files modified and services used'
  execution-path-json:
    description: 'JSON string containing the execution path data'

runs:
  using: 'node20'
  main: 'dist/index.js'
